### ISSUE TITLE
MD register to vote link is broken

### ISSUE THREAD

**Issue by tejans24** [presidential-innovation-fellows/vote-2016#113]
It currently shows a 404 ("The specified URL cannot be found.")
Should it be changed from https://voterservices.elections.state.md.us/OnlineVoterRegistration/VoterType?ref=voteusa to https://voterservices.elections.state.md.us/OnlineVoterRegistration?ref=voteusa ?

**Comment by ghost** [comment]
Hi @tejans24 I have checked the link its not broken but the voter registeration for the state of Maryland has been closed.Hence you are unable to register.I have attached the screenshot after checking the link
![mdvoting](https://cloud.githubusercontent.com/assets/10228512/14858799/78fb2daa-0c6f-11e6-9eb1-85387f4fefa7.PNG)

**Comment by ghost** [comment]
@tejans24 The correct url https://voterservices.elections.state.md.us/OnlineVoterRegistration/?ref=voteusa

**Comment by ghost** [comment]
@tejans24 the url needs to be changed!

**Comment by stroupaloop** [comment]
Fixed! Thanks for the pull request @tejans24
