### ISSUE TITLE
create an iframe icon for other sites to add to their websites

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/vote-2016#14]
Think something like Mixpanel code >

```
<a href="https://mixpanel.com/f/partner" id="mixpanel-logo">
  <img src="//cdn.mxpnl.com/site_media/images/partner/badge_light.png" alt="Mobile Analytics" />
</a>
```

Can dump it into S3 and use that reference link ... I think :)

**Comment by stroupaloop** [comment]
Need to also be able to track via analytics to understand traffic flow

**Comment by KateMcCall-Kiley** [comment]
Adding icon

![redirect-button1](https://cloud.githubusercontent.com/assets/13965725/9967889/46c6a5ae-5e13-11e5-97bb-f485c2ef7299.png)

**Comment by stroupaloop** [comment]
Awesome, thanks @KateMcCall-Kiley , will incorporate over the weekend as a tag.

**Comment by stroupaloop** [comment]
Uploaded and running

```
<a href="https://vote.usa.gov/">
  <img src="https://vote.usa.gov/images/vote-badge.png" alt="vote.USA.gov badge" />
</a>
```
