### ISSUE TITLE
Add in analytics

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/vote-2016#16]
We can coordinate with 18F (Gray Brooks) and usa.gov team on this one

**Comment by lukad03** [comment]
@stroupaloop assigning you since I don't have access to any GSA/gov analytics

**Comment by lukad03** [comment]
@stroupaloop do we want to include GA event tracking in this as well?

**Comment by stroupaloop** [comment]
5226652

**Comment by stroupaloop** [comment]
@lukad03 we could do that, not as familiar with GA event tracking because it can be a pain to deal with. May incorporate Mixpanel, but will create another issue to dig into GA events

**Comment by lukad03** [comment]
Do we have a Segment.io account? Would make tracking all of this much
simpler if we wanted to.

On Wed, Sep 16, 2015 at 3:51 PM, Andrew Stroup notifications@github.com
wrote:

> @lukad03 https://github.com/lukad03 we could do that, not as familiar
> with GA event tracking because it can be a pain to deal with. May
> incorporate Mixpanel, but will create another issue to dig into GA events
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/presidential-innovation-fellows/vote-2016/issues/16#issuecomment-140867842
> .

## 

Luke Keller
Presidential Innovation Fellow
