### ISSUE TITLE
Re-selecting the same state in the drop down should cause the modal to re-appear

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/vote-2016#22]

**Comment by lukad03** [comment]
So this is going to be  very difficult fix, perhaps impossible. The `change` event only fires when a select option is changed. I've tried binding `click` and `focus` on the `options`, but `option` doesn't accept most of those events.

The alternative would be to build an entirely custom `select` with `div`s and `js` to mitigate this issue, but that seems like unnecessary bloat.

**Comment by stroupaloop** [comment]
Does something like this resolve the issue? http://stackoverflow.com/questions/20354112/trigger-the-event-when-selected-the-same-value-in-dropdown

**Comment by lukad03** [comment]
Above solution doesn't work. Fires when clicking and before an option is selected.

**Comment by stroupaloop** [comment]
Seeing if I can resolve over the weekend :)
