### ISSUE TITLE
Twitter feed on hashtag

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/vote-2016#27]
Current hashtags
# GetRegistered
# NVRD

**Comment by lukad03** [comment]
Waiting for comms to get back to us

**Comment by stroupaloop** [comment]
https://twitter.com/settings/widgets/646189961016942592/edit?focus_textarea=1&notice=WIDGET_CREATED

need to figure out best implementation for Twitter widget or using Twitter's API js implementation
