### ISSUE TITLE
turbovote iframe design notes

### ISSUE THREAD

**Issue by SethAndrew** [presidential-innovation-fellows/vote-2016#54]
1) on the TurboVote Widget iframe the "Why are you registering to vote" page the font color for "this is my first time registering" is too light, it's hard to read
2) same for "where would you like to receive election materials"  and "what's your party"
3) once you click the "party" choice it is slow to load to the next page
4) on a chrome browser, the youtube video window partially obscured the TV widget. 
5) on the Congratulations page the "via text message" and "via email' check boxes appear next to each other instead of above each other 
6) it's not 100% clear what "save account settings" refers to.

**Comment by stroupaloop** [comment]
currently do not plan to make modifications to existing TurboVote code base due to OGC and leveraging the free, public version

**Comment by SethAndrew** [comment]
Understood. Thx.
s
