### ISSUE TITLE
video box overlapps Iframe 

### ISSUE THREAD

**Issue by SethAndrew** [presidential-innovation-fellows/vote-2016#55]
on some browsers but not others. on the left side of the iframe. might be resolved, but thought I'd mention it in case others see the issue.

**Comment by SethAndrew** [comment]
![overlap](https://cloud.githubusercontent.com/assets/12666182/9919965/6913e688-5c9e-11e5-9a15-a0eca8561d53.png)

**Comment by stroupaloop** [comment]
Believe this is resolved, please verify if still an issue, closing.
