### ISSUE TITLE
Maybe some info below the video/why vote section?

### ISSUE THREAD

**Issue by KateMcCall-Kiley** [presidential-innovation-fellows/vote-2016#73]
Attaching some thoughts but definitely open to change.  (All data was taken from publicly available census data)

![voting-info3-05](https://cloud.githubusercontent.com/assets/13965725/9984176/32a17156-5fe1-11e5-9a54-e6c2ef0583ce.png)
![voting-info3-01](https://cloud.githubusercontent.com/assets/13965725/9984178/3465c47e-5fe1-11e5-8399-6afbe6eb7a6f.png)
![voting-info3-04](https://cloud.githubusercontent.com/assets/13965725/9984179/36264b6c-5fe1-11e5-988f-0a6a86b2a467.png)
![voting-info3-02](https://cloud.githubusercontent.com/assets/13965725/9984180/37b47d96-5fe1-11e5-9e3d-529fd3018d0b.png)
![voting-info3-03](https://cloud.githubusercontent.com/assets/13965725/9984181/39242b90-5fe1-11e5-8414-65f024545caf.png)

**Comment by stroupaloop** [comment]
added in today
