### ISSUE TITLE
Update with new states that provide online voter registration

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/vote-2016#87]
Should be West Virginia and Nebraska

**Comment by stroupaloop** [comment]
I literally can't find West Virginia's online voter registration ... go government?

**Comment by stroupaloop** [comment]
make that Nebrasks too that apparently has hidden all their online voter registration if it was truly deployed according to this:

http://www.ncsl.org/research/elections-and-campaigns/electronic-or-online-voter-registration.aspx

**Comment by stroupaloop** [comment]
Nebraska has been updated > 6fa04a4

**Comment by rogeruiz** [comment]
I found West Virginia's registration link here => https://ovr.sos.wv.gov/Register#Landing

I can add this in a PR @stroupaloop :thought_balloon:

**Comment by stroupaloop** [comment]
Looks like it has already been updated and I think in general we can start closing this down as it's being monitored by others now :) thanks for pointing this out @rogeruiz
