### ISSUE TITLE
Update web content: negative > positive statistic

### ISSUE THREAD

**Issue by stroupaloop** [presidential-innovation-fellows/vote-2016#88]

**Comment by stroupaloop** [comment]
pinging @KateMcCall-Kiley for some awesome content to update this. Link on stats below

http://www.statisticbrain.com/voting-statistics/

**Comment by KateMcCall-Kiley** [comment]
How about the following:

over 146 million (h1)
Americans are ready to be heard this election season (h2)

The voting rate for those who are registered is 90%. Are you ready?  Join the movement and be heard.

**Comment by rogeruiz** [comment]
We're currently working on a content audit for the vote.gov site here 18F/vote-2016#2. I'm not sure if this issue needs to stay open @stroupaloop What do you think?

**Comment by stroupaloop** [comment]
Yep can close!
